### ISSUE TITLE
Adding a tag for composer support

### ISSUE THREAD

**Issue by hboomsma** [pear/PEAR_Exception#3]
To be able to use this package in a stable environment composer needs a tag with a version number like 1.0.0 or 1.0 or 1 or v1.0.0 etc. Could you please add a tag?

Would be nice if the version number actually matched the pear version number the file is in.

**Comment by kmelia** [comment]
:+1: 
When you get the package "pear/pear_exception" with composer it is always more simple and fast to get a tag instead of dev-master.
Can you create a tag and publish it on https://packagist.org/ ?

**Comment by cweiske** [comment]
1.0.0 is out and tagged.
